# Generated by Django 5.0.4 on 2024-05-14 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='home_catego_id_9c2304_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0, max_length=1)),
                ('comment', models.TextField()),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/client')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='home_client_id_c49adf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/profile')),
                ('address', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='home_profil_id_a3e7e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
                ('duration', models.DateField()),
                ('taken', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/product')),
                ('price_type', models.CharField(choices=[('EURO', 'EURO'), ('$', '$'), ('SO`M', 'SO`M')], max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0, max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='home_produc_id_e7e888_idx')],
            },
        ),
    ]
